version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8050:8050"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
      - ./backend/uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 